name: Testes Robot Framework
on: [push, pull_request]

jobs: 
  Test:
    runs-on: ubuntu-lastest
steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with: 
          robot_reports_dir: 'reports'
      
      - name: Resultado dos uploads de testes
        use: action/upload-artifact2@v2
        if: always()
        with:
          name: robotReport
          path: reports    